# Repo: andr317c/load-test-pipeline
# File: azure-pipeline.yml

name: load_test_pipeline

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure Service Connection (NEEDS TO BE CHANGED FROM MICROSOFT AZURE SPONSORSHIP TO UMBRACO SERVICES DEV)
  serviceConnection: 'terraform-umbraco-load-testing-azure-connection'
  # Backend Storage Account
  bkServiceConnection : 'terraform-umbraco-load-testing-tstate-azure-connection'
  bkstrgrg: 'andreas-load-test-tstate-rg'
  bkstrgname: 'loadtesttstate'
  bkcontainer: 'tfstate'
  bkstrgkey: 'fhaj3vRuoP8h/FTOHfg4AD84kExOPI+EL9cvoyl2KBl1ZGd5d0uAzoMiPntW10YTHMpvZhwR1RFT+AStKxULfQ=='

  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'

stages:
- stage: terraformValidate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest' 
    - task: TerraformTaskV4@4
      displayName: Initialize
      condition: succeeded()
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(terraformWorkingDirectory)'
        backendServiceArm: '$(bkServiceConnection)'
        backendAzureRmResourceGroupName: '$(bkstrgrg)'
        backendAzureRmStorageAccountName: '$(bkstrgname)'
        backendAzureRmContainerName: '$(bkcontainer)'
        backendAzureRmKey: '$(bkstrgkey)'
    - task: TerraformTaskV4@4
      displayName: Validate 
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(terraformWorkingDirectory)'

- stage: terraformDeploy
  condition: succeeded('terraformValidate')
  dependsOn: terraformValidate
  jobs:
    - job: setup 
      steps:
       - task: TerraformInstaller@0
         displayName: Install Terraform
         inputs:
          terraformVersion: 'latest' 
       - task: TerraformTaskV4@4
         displayName: Initialize
         condition: succeeded()
         inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(terraformWorkingDirectory)'
          backendServiceArm: '$(bkServiceConnection)'
          backendAzureRmResourceGroupName: '$(bkstrgrg)'
          backendAzureRmStorageAccountName: '$(bkstrgname)'
          backendAzureRmContainerName: '$(bkcontainer)'
          backendAzureRmKey: '$(bkstrgkey)'      
       - task: TerraformTaskV4@4
         displayName: Plan
         inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(terraformWorkingDirectory)'
          environmentServiceNameAzureRM: '$(serviceConnection)'
    - job: manualValidation
      steps:
       - task: ManualValidation@0
         displayName: Wait for external validation
         inputs:
           notifyUsers: aze@umbraco.dk
           instructions: 'Please validate that the terraform plan is correct'
    - job: apply
      steps:
       - task: TerraformTaskV4@4
         displayName: Apply
         inputs:
           provider: 'azurerm'
           command: 'apply'
           workingDirectory: '$(terraformWorkingDirectory)'
           environmentServiceNameAzureRM: '$(serviceConnection)'
  