# Repo: andr317c/load-test-pipeline
# File: azure-pipeline.yml

name: script_test_pipeline

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:

  # Terraform settings
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)/Terraform'
  # LoadTestLocation
  loadTestFileLocation: '$(System.DefaultWorkingDirectory)/LoadTestVersions.yaml'
  emptyString: '""'

stages:
- stage: scriptRun
  jobs:
    - job: runScript
      steps:
      
      - script: echo "##vso[task.setvariable variable=thirdDotNetVersion]null)" 
        displayName: update value if empty
        condition: eq(variables['thirdDotNetVersion'],'')

      - script: echo "$thirdDotNetVersion" 
      - script: echo "$emptyString" 

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: Write-Host -firstDotNetVersion $(firstDotNetVersion) -firstUmbracoVersion $(firstUmbracoVersion) -secondDotNetVersion $(secondDotNetVersion) -secondUmbracoVersion $(secondUmbracoVersion) -thirdDotNetVersion $(thirdDotNetVersion) -thirdUmbracoVersion $(thirdUmbracoVersion) -fourthDotNetVersion $(fourthDotNetVersion) -fourthUmbracoVersion $(fourthUmbracoVersion)
     # - task: PowerShell@2
     #   inputs:
     #     filePath: '$(terraformWorkingDirectory)/script/versionsToJson.ps1'
     #     arguments: '-firstDotNetVersion $(firstDotNetVersion) -firstUmbracoVersion $(firstUmbracoVersion) -secondDotNetVersion $(secondDotNetVersion) -secondUmbracoVersion $(secondUmbracoVersion) -thirdDotNetVersion $(thirdDotNetVersion) -thirdUmbracoVersion $(thirdUmbracoVersion) -fourthDotNetVersion $(fourthDotNetVersion) -fourthUmbracoVersion $(fourthUmbracoVersion)'